package com.wyd.domain;
// Generated May 3, 2018 2:37:09 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Company generated by hbm2java
 */
@Entity
@Table(name = "company", catalog = "points")
public class Company implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer companyId;
	private Status status;
	private String companyCd;
	private String companyName;
	private String companyDesc;
	private String companyTypeCd;
	private String electronicAddrTxt;
	private String createdById;
	private String lastUpdatedById;
	private Set<ProductMembership> productMemberships = new HashSet<ProductMembership>(0);
	private Set<Membership> memberships = new HashSet<Membership>(0);
	private Set<PointsTransHeader> pointsTransHeaders = new HashSet<PointsTransHeader>(0);
	private Set<TransPayment> transPayments = new HashSet<TransPayment>(0);

	public Company() {
	}

	public Company(Status status, String companyCd, String companyName, String companyTypeCd, String createdById,
			Date createdDttm, String lastUpdatedById, Date lastUpdatedDttm) {
		this.status = status;
		this.companyCd = companyCd;
		this.companyName = companyName;
		this.companyTypeCd = companyTypeCd;
		this.createdById = createdById;
		this.lastUpdatedById = lastUpdatedById;
	}

	public Company(Status status, String companyCd, String companyName, String companyDesc, String companyTypeCd,
			String electronicAddrTxt, String createdById, Date createdDttm, String lastUpdatedById,
			Date lastUpdatedDttm, Set<ProductMembership> productMemberships, Set<Membership> memberships,
			Set<PointsTransHeader> pointsTransHeaders, Set<TransPayment> transPayments) {
		this.status = status;
		this.companyCd = companyCd;
		this.companyName = companyName;
		this.companyDesc = companyDesc;
		this.companyTypeCd = companyTypeCd;
		this.electronicAddrTxt = electronicAddrTxt;
		this.createdById = createdById;
		this.lastUpdatedById = lastUpdatedById;
		this.productMemberships = productMemberships;
		this.memberships = memberships;
		this.pointsTransHeaders = pointsTransHeaders;
		this.transPayments = transPayments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "COMPANY_ID", unique = true, nullable = false)
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "STATUS_ID", nullable = false)
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@Column(name = "COMPANY_CD", nullable = false, length = 10)
	public String getCompanyCd() {
		return this.companyCd;
	}

	public void setCompanyCd(String companyCd) {
		this.companyCd = companyCd;
	}

	@Column(name = "COMPANY_NAME", nullable = false, length = 100)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "COMPANY_DESC", length = 250)
	public String getCompanyDesc() {
		return this.companyDesc;
	}

	public void setCompanyDesc(String companyDesc) {
		this.companyDesc = companyDesc;
	}

	@Column(name = "COMPANY_TYPE_CD", nullable = false, length = 10)
	public String getCompanyTypeCd() {
		return this.companyTypeCd;
	}

	public void setCompanyTypeCd(String companyTypeCd) {
		this.companyTypeCd = companyTypeCd;
	}

	@Column(name = "ELECTRONIC_ADDR_TXT", length = 100)
	public String getElectronicAddrTxt() {
		return this.electronicAddrTxt;
	}

	public void setElectronicAddrTxt(String electronicAddrTxt) {
		this.electronicAddrTxt = electronicAddrTxt;
	}

	@Column(name = "CREATED_BY_ID", nullable = false, length = 100)
	public String getCreatedById() {
		return this.createdById;
	}

	public void setCreatedById(String createdById) {
		this.createdById = createdById;
	}

	@Column(name = "LAST_UPDATED_BY_ID", nullable = false, length = 100)
	public String getLastUpdatedById() {
		return this.lastUpdatedById;
	}

	public void setLastUpdatedById(String lastUpdatedById) {
		this.lastUpdatedById = lastUpdatedById;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "company")
	@XmlTransient
	public Set<ProductMembership> getProductMemberships() {
		return this.productMemberships;
	}

	public void setProductMemberships(Set<ProductMembership> productMemberships) {
		this.productMemberships = productMemberships;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "company")
	@XmlTransient
	public Set<Membership> getMemberships() {
		return this.memberships;
	}

	public void setMemberships(Set<Membership> memberships) {
		this.memberships = memberships;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "company")
	@XmlTransient
	public Set<PointsTransHeader> getPointsTransHeaders() {
		return this.pointsTransHeaders;
	}

	public void setPointsTransHeaders(Set<PointsTransHeader> pointsTransHeaders) {
		this.pointsTransHeaders = pointsTransHeaders;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "company")
	@XmlTransient
	public Set<TransPayment> getTransPayments() {
		return this.transPayments;
	}

	public void setTransPayments(Set<TransPayment> transPayments) {
		this.transPayments = transPayments;
	}

}
