package com.wyd.domain;
// Generated May 3, 2018 2:37:09 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlTransient;

/**
 * PaymentMethod generated by hbm2java
 */
@Entity
@Table(name = "payment_method", catalog = "points")
public class PaymentMethod implements java.io.Serializable {

	private static final long serialVersionUID = 6366368410109998785L;
	
	private String paymentMethodCd;
	private String paymentMethodDesc;
	private int activeInd;
	private Date lastUpdatedDttm;
	private String lastUpdatedById;
	private Set<TransPayment> transPayments = new HashSet<TransPayment>(0);

	public PaymentMethod() {
	}

	public PaymentMethod(String paymentMethodCd, int activeInd, Date lastUpdatedDttm, String lastUpdatedById) {
		this.paymentMethodCd = paymentMethodCd;
		this.activeInd = activeInd;
		this.lastUpdatedDttm = lastUpdatedDttm;
		this.lastUpdatedById = lastUpdatedById;
	}

	public PaymentMethod(String paymentMethodCd, String paymentMethodDesc, int activeInd, Date lastUpdatedDttm,
			String lastUpdatedById, Set<TransPayment> transPayments) {
		this.paymentMethodCd = paymentMethodCd;
		this.paymentMethodDesc = paymentMethodDesc;
		this.activeInd = activeInd;
		this.lastUpdatedDttm = lastUpdatedDttm;
		this.lastUpdatedById = lastUpdatedById;
		this.transPayments = transPayments;
	}

	@Id

	@Column(name = "PAYMENT_METHOD_CD", unique = true, nullable = false, length = 10)
	public String getPaymentMethodCd() {
		return this.paymentMethodCd;
	}

	public void setPaymentMethodCd(String paymentMethodCd) {
		this.paymentMethodCd = paymentMethodCd;
	}

	@Column(name = "PAYMENT_METHOD_DESC", length = 250)
	public String getPaymentMethodDesc() {
		return this.paymentMethodDesc;
	}

	public void setPaymentMethodDesc(String paymentMethodDesc) {
		this.paymentMethodDesc = paymentMethodDesc;
	}

	@Column(name = "ACTIVE_IND", nullable = false)
	public int getActiveInd() {
		return this.activeInd;
	}

	public void setActiveInd(int activeInd) {
		this.activeInd = activeInd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_DTTM", nullable = false, length = 19)
	public Date getLastUpdatedDttm() {
		return this.lastUpdatedDttm;
	}

	public void setLastUpdatedDttm(Date lastUpdatedDttm) {
		this.lastUpdatedDttm = lastUpdatedDttm;
	}

	@Column(name = "LAST_UPDATED_BY_ID", nullable = false, length = 100)
	public String getLastUpdatedById() {
		return this.lastUpdatedById;
	}

	public void setLastUpdatedById(String lastUpdatedById) {
		this.lastUpdatedById = lastUpdatedById;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "paymentMethod")
	@XmlTransient
	public Set<TransPayment> getTransPayments() {
		return this.transPayments;
	}

	public void setTransPayments(Set<TransPayment> transPayments) {
		this.transPayments = transPayments;
	}

}
