package com.wyd.domain;
// Generated May 3, 2018 2:37:09 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlTransient;

/**
 * PointsDepositTransDetail generated by hbm2java
 */
@Entity
@Table(name = "points_deposit_trans_detail", catalog = "points")
public class PointsDepositTransDetail implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer pointsDepositTransDetailId;
	private PointsAccount pointsAccount;
	private PointsSpendTransDetail pointsSpendTransDetail;
	private PointsTransHeader pointsTransHeader;
	private TransType transType;
	private TransactionDetail transactionDetail;
	private Integer referencePointsDepositId;
	private String pointsTypeCd;
	private Date effectiveStartDttm;
	private Date effectiveEndDttm;
	private BigDecimal pointsDepositTransQty;
	private int verificationInd;
	private String createdById;
	private Date createdDttm;
	private String lastUpdatedById;
	private Date lastUpdatedDttm;
	private Set<PointsSpendTransDetail> pointsSpendTransDetails = new HashSet<PointsSpendTransDetail>(0);

	public PointsDepositTransDetail() {
	}

	public PointsDepositTransDetail(PointsAccount pointsAccount, PointsTransHeader pointsTransHeader,
			TransType transType, String pointsTypeCd, Date effectiveStartDttm, Date effectiveEndDttm,
			int verificationInd, String createdById, Date createdDttm, String lastUpdatedById, Date lastUpdatedDttm) {
		this.pointsAccount = pointsAccount;
		this.pointsTransHeader = pointsTransHeader;
		this.transType = transType;
		this.pointsTypeCd = pointsTypeCd;
		this.effectiveStartDttm = effectiveStartDttm;
		this.effectiveEndDttm = effectiveEndDttm;
		this.verificationInd = verificationInd;
		this.createdById = createdById;
		this.createdDttm = createdDttm;
		this.lastUpdatedById = lastUpdatedById;
		this.lastUpdatedDttm = lastUpdatedDttm;
	}

	public PointsDepositTransDetail(PointsAccount pointsAccount, PointsSpendTransDetail pointsSpendTransDetail,
			PointsTransHeader pointsTransHeader, TransType transType, TransactionDetail transactionDetail,
			Integer referencePointsDepositId, String pointsTypeCd, Date effectiveStartDttm, Date effectiveEndDttm,
			BigDecimal pointsDepositTransQty, int verificationInd, String createdById, Date createdDttm,
			String lastUpdatedById, Date lastUpdatedDttm, Set<PointsSpendTransDetail> pointsSpendTransDetails) {
		this.pointsAccount = pointsAccount;
		this.pointsSpendTransDetail = pointsSpendTransDetail;
		this.pointsTransHeader = pointsTransHeader;
		this.transType = transType;
		this.transactionDetail = transactionDetail;
		this.referencePointsDepositId = referencePointsDepositId;
		this.pointsTypeCd = pointsTypeCd;
		this.effectiveStartDttm = effectiveStartDttm;
		this.effectiveEndDttm = effectiveEndDttm;
		this.pointsDepositTransQty = pointsDepositTransQty;
		this.verificationInd = verificationInd;
		this.createdById = createdById;
		this.createdDttm = createdDttm;
		this.lastUpdatedById = lastUpdatedById;
		this.lastUpdatedDttm = lastUpdatedDttm;
		this.pointsSpendTransDetails = pointsSpendTransDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "POINTS_DEPOSIT_TRANS_DETAIL_ID", unique = true, nullable = false)
	public Integer getPointsDepositTransDetailId() {
		return this.pointsDepositTransDetailId;
	}

	public void setPointsDepositTransDetailId(Integer pointsDepositTransDetailId) {
		this.pointsDepositTransDetailId = pointsDepositTransDetailId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "POINTS_ACCOUNT_ID", nullable = false)
	public PointsAccount getPointsAccount() {
		return this.pointsAccount;
	}

	public void setPointsAccount(PointsAccount pointsAccount) {
		this.pointsAccount = pointsAccount;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "POINTS_SPEND_TRANS_DETAIL_ID")
	public PointsSpendTransDetail getPointsSpendTransDetail() {
		return this.pointsSpendTransDetail;
	}

	public void setPointsSpendTransDetail(PointsSpendTransDetail pointsSpendTransDetail) {
		this.pointsSpendTransDetail = pointsSpendTransDetail;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "POINTS_TRANS_HEADER_ID", nullable = false)
	public PointsTransHeader getPointsTransHeader() {
		return this.pointsTransHeader;
	}

	public void setPointsTransHeader(PointsTransHeader pointsTransHeader) {
		this.pointsTransHeader = pointsTransHeader;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "TRANS_TYPE_ID", nullable = false)
	public TransType getTransType() {
		return this.transType;
	}

	public void setTransType(TransType transType) {
		this.transType = transType;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "TRANSACTION_ID")
	public TransactionDetail getTransactionDetail() {
		return this.transactionDetail;
	}

	public void setTransactionDetail(TransactionDetail transactionDetail) {
		this.transactionDetail = transactionDetail;
	}

	@Column(name = "REFERENCE_POINTS_DEPOSIT_ID")
	public Integer getReferencePointsDepositId() {
		return this.referencePointsDepositId;
	}

	public void setReferencePointsDepositId(Integer referencePointsDepositId) {
		this.referencePointsDepositId = referencePointsDepositId;
	}

	@Column(name = "POINTS_TYPE_CD", nullable = false, length = 10)
	public String getPointsTypeCd() {
		return this.pointsTypeCd;
	}

	public void setPointsTypeCd(String pointsTypeCd) {
		this.pointsTypeCd = pointsTypeCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EFFECTIVE_START_DTTM", nullable = false, length = 19)
	public Date getEffectiveStartDttm() {
		return this.effectiveStartDttm;
	}

	public void setEffectiveStartDttm(Date effectiveStartDttm) {
		this.effectiveStartDttm = effectiveStartDttm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EFFECTIVE_END_DTTM", nullable = false, length = 19)
	public Date getEffectiveEndDttm() {
		return this.effectiveEndDttm;
	}

	public void setEffectiveEndDttm(Date effectiveEndDttm) {
		this.effectiveEndDttm = effectiveEndDttm;
	}

	@Column(name = "POINTS_DEPOSIT_TRANS_QTY", precision = 18, scale = 4)
	public BigDecimal getPointsDepositTransQty() {
		return this.pointsDepositTransQty;
	}

	public void setPointsDepositTransQty(BigDecimal pointsDepositTransQty) {
		this.pointsDepositTransQty = pointsDepositTransQty;
	}

	@Column(name = "VERIFICATION_IND", nullable = false)
	public int getVerificationInd() {
		return this.verificationInd;
	}

	public void setVerificationInd(int verificationInd) {
		this.verificationInd = verificationInd;
	}

	@Column(name = "CREATED_BY_ID", nullable = false, length = 100)
	public String getCreatedById() {
		return this.createdById;
	}

	public void setCreatedById(String createdById) {
		this.createdById = createdById;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DTTM", nullable = false, length = 19)
	public Date getCreatedDttm() {
		return this.createdDttm;
	}

	public void setCreatedDttm(Date createdDttm) {
		this.createdDttm = createdDttm;
	}

	@Column(name = "LAST_UPDATED_BY_ID", nullable = false, length = 100)
	public String getLastUpdatedById() {
		return this.lastUpdatedById;
	}

	public void setLastUpdatedById(String lastUpdatedById) {
		this.lastUpdatedById = lastUpdatedById;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_DTTM", nullable = false, length = 19)
	public Date getLastUpdatedDttm() {
		return this.lastUpdatedDttm;
	}

	public void setLastUpdatedDttm(Date lastUpdatedDttm) {
		this.lastUpdatedDttm = lastUpdatedDttm;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "pointsDepositTransDetail")
	@XmlTransient
	public Set<PointsSpendTransDetail> getPointsSpendTransDetails() {
		return this.pointsSpendTransDetails;
	}

	public void setPointsSpendTransDetails(Set<PointsSpendTransDetail> pointsSpendTransDetails) {
		this.pointsSpendTransDetails = pointsSpendTransDetails;
	}

}
