package com.wyd.domain;
// Generated May 3, 2018 2:37:09 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlTransient;

/**
 * PointsAccountType generated by hbm2java
 */
@Entity
@Table(name = "points_account_type", catalog = "points")
public class PointsAccountType implements java.io.Serializable {

	private static final long serialVersionUID = -4862666042829167954L;
	
	private String pointsAccountTypeCd;
	private String pointsAccountTypeDesc;
	private String createdById;
	private Date createdDttm;
	private String lastUpdatedById;
	private Date lastUpdatedDttm;
	private Set<PointsAccount> pointsAccounts = new HashSet<PointsAccount>(0);

	public PointsAccountType() {
	}

	public PointsAccountType(String pointsAccountTypeCd, String pointsAccountTypeDesc, String createdById,
			Date createdDttm, String lastUpdatedById, Date lastUpdatedDttm) {
		this.pointsAccountTypeCd = pointsAccountTypeCd;
		this.pointsAccountTypeDesc = pointsAccountTypeDesc;
		this.createdById = createdById;
		this.createdDttm = createdDttm;
		this.lastUpdatedById = lastUpdatedById;
		this.lastUpdatedDttm = lastUpdatedDttm;
	}

	public PointsAccountType(String pointsAccountTypeCd, String pointsAccountTypeDesc, String createdById,
			Date createdDttm, String lastUpdatedById, Date lastUpdatedDttm, Set<PointsAccount> pointsAccounts) {
		this.pointsAccountTypeCd = pointsAccountTypeCd;
		this.pointsAccountTypeDesc = pointsAccountTypeDesc;
		this.createdById = createdById;
		this.createdDttm = createdDttm;
		this.lastUpdatedById = lastUpdatedById;
		this.lastUpdatedDttm = lastUpdatedDttm;
		this.pointsAccounts = pointsAccounts;
	}

	@Id

	@Column(name = "POINTS_ACCOUNT_TYPE_CD", unique = true, nullable = false, length = 10)
	public String getPointsAccountTypeCd() {
		return this.pointsAccountTypeCd;
	}

	public void setPointsAccountTypeCd(String pointsAccountTypeCd) {
		this.pointsAccountTypeCd = pointsAccountTypeCd;
	}

	@Column(name = "POINTS_ACCOUNT_TYPE_DESC", nullable = false, length = 100)
	public String getPointsAccountTypeDesc() {
		return this.pointsAccountTypeDesc;
	}

	public void setPointsAccountTypeDesc(String pointsAccountTypeDesc) {
		this.pointsAccountTypeDesc = pointsAccountTypeDesc;
	}

	@Column(name = "CREATED_BY_ID", nullable = false, length = 100)
	public String getCreatedById() {
		return this.createdById;
	}

	public void setCreatedById(String createdById) {
		this.createdById = createdById;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DTTM", nullable = false, length = 19)
	public Date getCreatedDttm() {
		return this.createdDttm;
	}

	public void setCreatedDttm(Date createdDttm) {
		this.createdDttm = createdDttm;
	}

	@Column(name = "LAST_UPDATED_BY_ID", nullable = false, length = 100)
	public String getLastUpdatedById() {
		return this.lastUpdatedById;
	}

	public void setLastUpdatedById(String lastUpdatedById) {
		this.lastUpdatedById = lastUpdatedById;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_DTTM", nullable = false, length = 19)
	public Date getLastUpdatedDttm() {
		return this.lastUpdatedDttm;
	}

	public void setLastUpdatedDttm(Date lastUpdatedDttm) {
		this.lastUpdatedDttm = lastUpdatedDttm;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "pointsAccountType")
	@XmlTransient
	public Set<PointsAccount> getPointsAccounts() {
		return this.pointsAccounts;
	}

	public void setPointsAccounts(Set<PointsAccount> pointsAccounts) {
		this.pointsAccounts = pointsAccounts;
	}

}
