package com.wyd.domain;
// Generated May 3, 2018 2:37:09 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "points")
public class Product implements java.io.Serializable {

	private static final long serialVersionUID = 6272898072113206429L;
	
	private Integer productId;
	private Status status;
	private String productCd;
	private String productName;
	private String productDesc;
	private Date effectiveStartDttm;
	private Date effectiveEndDttm;
	private String createdById;
	private Date createdDttm;
	private String lastUpdatedById;
	private Date lastUpdatedDttm;
	private Set<ProductMembership> productMemberships = new HashSet<ProductMembership>(0);

	public Product() {
	}

	public Product(Status status, String productCd, String productName, String createdById, Date createdDttm,
			String lastUpdatedById, Date lastUpdatedDttm) {
		this.status = status;
		this.productCd = productCd;
		this.productName = productName;
		this.createdById = createdById;
		this.createdDttm = createdDttm;
		this.lastUpdatedById = lastUpdatedById;
		this.lastUpdatedDttm = lastUpdatedDttm;
	}

	public Product(Status status, String productCd, String productName, String productDesc, Date effectiveStartDttm,
			Date effectiveEndDttm, String createdById, Date createdDttm, String lastUpdatedById, Date lastUpdatedDttm,
			Set<ProductMembership> productMemberships) {
		this.status = status;
		this.productCd = productCd;
		this.productName = productName;
		this.productDesc = productDesc;
		this.effectiveStartDttm = effectiveStartDttm;
		this.effectiveEndDttm = effectiveEndDttm;
		this.createdById = createdById;
		this.createdDttm = createdDttm;
		this.lastUpdatedById = lastUpdatedById;
		this.lastUpdatedDttm = lastUpdatedDttm;
		this.productMemberships = productMemberships;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PRODUCT_ID", unique = true, nullable = false)
	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "STATUS_ID", nullable = false)
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@Column(name = "PRODUCT_CD", nullable = false, length = 10)
	public String getProductCd() {
		return this.productCd;
	}

	public void setProductCd(String productCd) {
		this.productCd = productCd;
	}

	@Column(name = "PRODUCT_NAME", nullable = false, length = 100)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "PRODUCT_DESC", length = 250)
	public String getProductDesc() {
		return this.productDesc;
	}

	public void setProductDesc(String productDesc) {
		this.productDesc = productDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EFFECTIVE_START_DTTM", length = 19)
	public Date getEffectiveStartDttm() {
		return this.effectiveStartDttm;
	}

	public void setEffectiveStartDttm(Date effectiveStartDttm) {
		this.effectiveStartDttm = effectiveStartDttm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EFFECTIVE_END_DTTM", length = 19)
	public Date getEffectiveEndDttm() {
		return this.effectiveEndDttm;
	}

	public void setEffectiveEndDttm(Date effectiveEndDttm) {
		this.effectiveEndDttm = effectiveEndDttm;
	}

	@Column(name = "CREATED_BY_ID", nullable = false, length = 100)
	public String getCreatedById() {
		return this.createdById;
	}

	public void setCreatedById(String createdById) {
		this.createdById = createdById;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DTTM", nullable = false, length = 19)
	public Date getCreatedDttm() {
		return this.createdDttm;
	}

	public void setCreatedDttm(Date createdDttm) {
		this.createdDttm = createdDttm;
	}

	@Column(name = "LAST_UPDATED_BY_ID", nullable = false, length = 100)
	public String getLastUpdatedById() {
		return this.lastUpdatedById;
	}

	public void setLastUpdatedById(String lastUpdatedById) {
		this.lastUpdatedById = lastUpdatedById;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_DTTM", nullable = false, length = 19)
	public Date getLastUpdatedDttm() {
		return this.lastUpdatedDttm;
	}

	public void setLastUpdatedDttm(Date lastUpdatedDttm) {
		this.lastUpdatedDttm = lastUpdatedDttm;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "product")
	@XmlTransient
	public Set<ProductMembership> getProductMemberships() {
		return this.productMemberships;
	}

	public void setProductMemberships(Set<ProductMembership> productMemberships) {
		this.productMemberships = productMemberships;
	}

}
