package com.wyd.domain;
// Generated May 3, 2018 2:37:09 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlTransient;

/**
 * ProductMembership generated by hbm2java
 */
@Entity
@Table(name = "product_membership", catalog = "points")
public class ProductMembership implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer productMembershipId;
	private Company company;
	private Membership membership;
	private Product product;
	private Status status;
	private Date initialDttm;
	private Date expirationDttm;
	private String billingEntityCd;
	private int autoRenewalInd;
	private String createdById;
	private Date createdDttm;
	private String lastUpdatedById;
	private Date lastUpdatedDttm;
	private Date curEffectiveDttm;
	private Set<TransactionDetail> transactionDetails = new HashSet<TransactionDetail>(0);

	public ProductMembership() {
	}

	public ProductMembership(Membership membership, Product product, Status status, Date initialDttm,
			Date expirationDttm, int autoRenewalInd, String createdById, Date createdDttm, String lastUpdatedById,
			Date lastUpdatedDttm, Date curEffectiveDttm) {
		this.membership = membership;
		this.product = product;
		this.status = status;
		this.initialDttm = initialDttm;
		this.expirationDttm = expirationDttm;
		this.autoRenewalInd = autoRenewalInd;
		this.createdById = createdById;
		this.createdDttm = createdDttm;
		this.lastUpdatedById = lastUpdatedById;
		this.lastUpdatedDttm = lastUpdatedDttm;
		this.curEffectiveDttm = curEffectiveDttm;
	}

	public ProductMembership(Company company, Membership membership, Product product, Status status, Date initialDttm,
			Date expirationDttm, String billingEntityCd, int autoRenewalInd, String createdById, Date createdDttm,
			String lastUpdatedById, Date lastUpdatedDttm, Date curEffectiveDttm,
			Set<TransactionDetail> transactionDetails) {
		this.company = company;
		this.membership = membership;
		this.product = product;
		this.status = status;
		this.initialDttm = initialDttm;
		this.expirationDttm = expirationDttm;
		this.billingEntityCd = billingEntityCd;
		this.autoRenewalInd = autoRenewalInd;
		this.createdById = createdById;
		this.createdDttm = createdDttm;
		this.lastUpdatedById = lastUpdatedById;
		this.lastUpdatedDttm = lastUpdatedDttm;
		this.curEffectiveDttm = curEffectiveDttm;
		this.transactionDetails = transactionDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PRODUCT_MEMBERSHIP_ID", unique = true, nullable = false)
	public Integer getProductMembershipId() {
		return this.productMembershipId;
	}

	public void setProductMembershipId(Integer productMembershipId) {
		this.productMembershipId = productMembershipId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "COMPANY_ID")
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "MEMBERSHIP_ID", nullable = false)
	public Membership getMembership() {
		return this.membership;
	}

	public void setMembership(Membership membership) {
		this.membership = membership;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PRODUCT_ID", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "STATUS_ID", nullable = false)
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INITIAL_DTTM", nullable = false, length = 19)
	public Date getInitialDttm() {
		return this.initialDttm;
	}

	public void setInitialDttm(Date initialDttm) {
		this.initialDttm = initialDttm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EXPIRATION_DTTM", nullable = false, length = 19)
	public Date getExpirationDttm() {
		return this.expirationDttm;
	}

	public void setExpirationDttm(Date expirationDttm) {
		this.expirationDttm = expirationDttm;
	}

	@Column(name = "BILLING_ENTITY_CD", length = 10)
	public String getBillingEntityCd() {
		return this.billingEntityCd;
	}

	public void setBillingEntityCd(String billingEntityCd) {
		this.billingEntityCd = billingEntityCd;
	}

	@Column(name = "AUTO_RENEWAL_IND", nullable = false)
	public int getAutoRenewalInd() {
		return this.autoRenewalInd;
	}

	public void setAutoRenewalInd(int autoRenewalInd) {
		this.autoRenewalInd = autoRenewalInd;
	}

	@Column(name = "CREATED_BY_ID", nullable = false, length = 100)
	public String getCreatedById() {
		return this.createdById;
	}

	public void setCreatedById(String createdById) {
		this.createdById = createdById;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DTTM", nullable = false, length = 19)
	public Date getCreatedDttm() {
		return this.createdDttm;
	}

	public void setCreatedDttm(Date createdDttm) {
		this.createdDttm = createdDttm;
	}

	@Column(name = "LAST_UPDATED_BY_ID", nullable = false, length = 100)
	public String getLastUpdatedById() {
		return this.lastUpdatedById;
	}

	public void setLastUpdatedById(String lastUpdatedById) {
		this.lastUpdatedById = lastUpdatedById;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_DTTM", nullable = false, length = 19)
	public Date getLastUpdatedDttm() {
		return this.lastUpdatedDttm;
	}

	public void setLastUpdatedDttm(Date lastUpdatedDttm) {
		this.lastUpdatedDttm = lastUpdatedDttm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CUR_EFFECTIVE_DTTM", nullable = false, length = 19)
	public Date getCurEffectiveDttm() {
		return this.curEffectiveDttm;
	}

	public void setCurEffectiveDttm(Date curEffectiveDttm) {
		this.curEffectiveDttm = curEffectiveDttm;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "productMembership")
	@XmlTransient
	public Set<TransactionDetail> getTransactionDetails() {
		return this.transactionDetails;
	}

	public void setTransactionDetails(Set<TransactionDetail> transactionDetails) {
		this.transactionDetails = transactionDetails;
	}

}
