package com.wyd.domain;
// Generated May 3, 2018 2:37:09 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Program generated by hbm2java
 */
@Entity
@Table(name = "program", catalog = "points")
public class Program implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer programId;
	private String programCd;
	private String programName;
	private String createdById;
	private Date createdDttm;
	private String lastUpdatedById;
	private Date lastUpdatedDttm;
	private Set<PointsAccount> pointsAccounts = new HashSet<PointsAccount>(0);

	public Program() {
	}

	public Program(String programCd, String programName, String createdById, Date createdDttm, String lastUpdatedById,
			Date lastUpdatedDttm) {
		this.programCd = programCd;
		this.programName = programName;
		this.createdById = createdById;
		this.createdDttm = createdDttm;
		this.lastUpdatedById = lastUpdatedById;
		this.lastUpdatedDttm = lastUpdatedDttm;
	}

	public Program(String programCd, String programName, String createdById, Date createdDttm, String lastUpdatedById,
			Date lastUpdatedDttm, Set<PointsAccount> pointsAccounts) {
		this.programCd = programCd;
		this.programName = programName;
		this.createdById = createdById;
		this.createdDttm = createdDttm;
		this.lastUpdatedById = lastUpdatedById;
		this.lastUpdatedDttm = lastUpdatedDttm;
		this.pointsAccounts = pointsAccounts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PROGRAM_ID", unique = true, nullable = false)
	public Integer getProgramId() {
		return this.programId;
	}

	public void setProgramId(Integer programId) {
		this.programId = programId;
	}

	@Column(name = "PROGRAM_CD", nullable = false, length = 10)
	public String getProgramCd() {
		return this.programCd;
	}

	public void setProgramCd(String programCd) {
		this.programCd = programCd;
	}

	@Column(name = "PROGRAM_NAME", nullable = false, length = 100)
	public String getProgramName() {
		return this.programName;
	}

	public void setProgramName(String programName) {
		this.programName = programName;
	}

	@Column(name = "CREATED_BY_ID", nullable = false, length = 100)
	public String getCreatedById() {
		return this.createdById;
	}

	public void setCreatedById(String createdById) {
		this.createdById = createdById;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DTTM", nullable = false, length = 19)
	public Date getCreatedDttm() {
		return this.createdDttm;
	}

	public void setCreatedDttm(Date createdDttm) {
		this.createdDttm = createdDttm;
	}

	@Column(name = "LAST_UPDATED_BY_ID", nullable = false, length = 100)
	public String getLastUpdatedById() {
		return this.lastUpdatedById;
	}

	public void setLastUpdatedById(String lastUpdatedById) {
		this.lastUpdatedById = lastUpdatedById;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_DTTM", nullable = false, length = 19)
	public Date getLastUpdatedDttm() {
		return this.lastUpdatedDttm;
	}

	public void setLastUpdatedDttm(Date lastUpdatedDttm) {
		this.lastUpdatedDttm = lastUpdatedDttm;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "program")
	@XmlTransient
	public Set<PointsAccount> getPointsAccounts() {
		return this.pointsAccounts;
	}

	public void setPointsAccounts(Set<PointsAccount> pointsAccounts) {
		this.pointsAccounts = pointsAccounts;
	}

}
