package com.wyd.domain;
// Generated May 3, 2018 2:37:09 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "status", catalog = "points", uniqueConstraints = @UniqueConstraint(columnNames = { "STATUS_CD",
		"STATUS_CAT_NAME" }))
public class Status implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer statusId;
	private String statusCd;
	private String statusCatName;
	private String statusDefinitionDesc;
	private Integer activeInd;
	private String createdById;
	private String lastUpdatedById;
	private Set<Company> companies = new HashSet<Company>(0);
	private Set<ProductMembership> productMemberships = new HashSet<ProductMembership>(0);
	private Set<TransPayment> transPayments = new HashSet<TransPayment>(0);
	private Set<Product> products = new HashSet<Product>(0);
	private Set<Membership> memberships = new HashSet<Membership>(0);
	private Set<PointsAccount> pointsAccounts = new HashSet<PointsAccount>(0);

	public Status() {
	}

	public Status(String statusCd, String statusCatName, String createdById, Date createdDttm, String lastUpdatedById,
			Date lastUpdatedDttm) {
		this.statusCd = statusCd;
		this.statusCatName = statusCatName;
		this.createdById = createdById;
		this.lastUpdatedById = lastUpdatedById;
	}

	public Status(String statusCd, String statusCatName, String statusDefinitionDesc, Integer activeInd,
			String createdById, Date createdDttm, String lastUpdatedById, Date lastUpdatedDttm, Set<Company> companies,
			Set<ProductMembership> productMemberships, Set<TransPayment> transPayments, Set<Product> products,
			Set<Membership> memberships, Set<PointsAccount> pointsAccounts) {
		this.statusCd = statusCd;
		this.statusCatName = statusCatName;
		this.statusDefinitionDesc = statusDefinitionDesc;
		this.activeInd = activeInd;
		this.createdById = createdById;
		this.lastUpdatedById = lastUpdatedById;
		this.companies = companies;
		this.productMemberships = productMemberships;
		this.transPayments = transPayments;
		this.products = products;
		this.memberships = memberships;
		this.pointsAccounts = pointsAccounts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "STATUS_ID", unique = true, nullable = false)
	public Integer getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	@Column(name = "STATUS_CD", nullable = false, length = 10)
	public String getStatusCd() {
		return this.statusCd;
	}

	public void setStatusCd(String statusCd) {
		this.statusCd = statusCd;
	}

	@Column(name = "STATUS_CAT_NAME", nullable = false, length = 100)
	public String getStatusCatName() {
		return this.statusCatName;
	}

	public void setStatusCatName(String statusCatName) {
		this.statusCatName = statusCatName;
	}

	@Column(name = "STATUS_DEFINITION_DESC", length = 250)
	public String getStatusDefinitionDesc() {
		return this.statusDefinitionDesc;
	}

	public void setStatusDefinitionDesc(String statusDefinitionDesc) {
		this.statusDefinitionDesc = statusDefinitionDesc;
	}

	@Column(name = "ACTIVE_IND")
	public Integer getActiveInd() {
		return this.activeInd;
	}

	public void setActiveInd(Integer activeInd) {
		this.activeInd = activeInd;
	}

	@Column(name = "CREATED_BY_ID", nullable = false, length = 100)
	public String getCreatedById() {
		return this.createdById;
	}

	public void setCreatedById(String createdById) {
		this.createdById = createdById;
	}

	@Column(name = "LAST_UPDATED_BY_ID", nullable = false, length = 100)
	public String getLastUpdatedById() {
		return this.lastUpdatedById;
	}

	public void setLastUpdatedById(String lastUpdatedById) {
		this.lastUpdatedById = lastUpdatedById;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "status")
	@XmlTransient
	public Set<Company> getCompanies() {
		return this.companies;
	}

	public void setCompanies(Set<Company> companies) {
		this.companies = companies;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "status")
	@XmlTransient
	public Set<ProductMembership> getProductMemberships() {
		return this.productMemberships;
	}

	public void setProductMemberships(Set<ProductMembership> productMemberships) {
		this.productMemberships = productMemberships;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "status")
	@XmlTransient
	public Set<TransPayment> getTransPayments() {
		return this.transPayments;
	}

	public void setTransPayments(Set<TransPayment> transPayments) {
		this.transPayments = transPayments;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "status")
	@XmlTransient
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "status")
	@XmlTransient
	public Set<Membership> getMemberships() {
		return this.memberships;
	}

	public void setMemberships(Set<Membership> memberships) {
		this.memberships = memberships;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "status")
	@XmlTransient
	public Set<PointsAccount> getPointsAccounts() {
		return this.pointsAccounts;
	}

	public void setPointsAccounts(Set<PointsAccount> pointsAccounts) {
		this.pointsAccounts = pointsAccounts;
	}
	
}
