package com.wyd.domain;
// Generated May 14, 2018 6:34:28 PM by Hibernate Tools 5.2.8.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;;

/**
 * Store generated by hbm2java
 */
@Entity
@Table(name = "store", catalog = "points")
public class Store implements java.io.Serializable {

	private static final long serialVersionUID = -184631661811839289L;
	
	private Integer storeId;
	private String storeName;
	private Float strategy;

	public Store() {
	}

	public Store(String storeName, Float strategy) {
		this.storeName = storeName;
		this.strategy = strategy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "STORE_ID", unique = true, nullable = false)
	public Integer getStoreId() {
		return this.storeId;
	}

	public void setStoreId(Integer storeId) {
		this.storeId = storeId;
	}

	@Column(name = "STORE_NAME", nullable = false, length = 100)
	public String getStoreName() {
		return this.storeName;
	}

	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}

	@Column(name = "STRATEGY", nullable = false, precision = 12, scale = 0)
	public Float getStrategy() {
		return this.strategy;
	}

	public void setStrategy(Float strategy) {
		this.strategy = strategy;
	}

}
