package com.wyd.domain;
// Generated May 3, 2018 2:37:09 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TransDetailPayment generated by hbm2java
 */
@Entity
@Table(name = "trans_detail_payment", catalog = "points")
public class TransDetailPayment implements java.io.Serializable {

	private static final long serialVersionUID = -140548778747149532L;
	
	private Integer transDetailPaymentId;
	private Membership membership;
	private TransPayment transPayment;
	private TransactionDetail transactionDetail;
	private BigDecimal paymentAmt;
	private Date lastUpdatedDttm;
	private String lastUpdatedById;
	private Date createdDttm;
	private String createdById;
	private Integer creditTransDetailId;

	public TransDetailPayment() {
	}

	public TransDetailPayment(TransPayment transPayment, TransactionDetail transactionDetail, Date lastUpdatedDttm,
			String lastUpdatedById, Date createdDttm, String createdById) {
		this.transPayment = transPayment;
		this.transactionDetail = transactionDetail;
		this.lastUpdatedDttm = lastUpdatedDttm;
		this.lastUpdatedById = lastUpdatedById;
		this.createdDttm = createdDttm;
		this.createdById = createdById;
	}

	public TransDetailPayment(Membership membership, TransPayment transPayment, TransactionDetail transactionDetail,
			BigDecimal paymentAmt, Date lastUpdatedDttm, String lastUpdatedById, Date createdDttm, String createdById,
			Integer creditTransDetailId) {
		this.membership = membership;
		this.transPayment = transPayment;
		this.transactionDetail = transactionDetail;
		this.paymentAmt = paymentAmt;
		this.lastUpdatedDttm = lastUpdatedDttm;
		this.lastUpdatedById = lastUpdatedById;
		this.createdDttm = createdDttm;
		this.createdById = createdById;
		this.creditTransDetailId = creditTransDetailId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "TRANS_DETAIL_PAYMENT_ID", unique = true, nullable = false)
	public Integer getTransDetailPaymentId() {
		return this.transDetailPaymentId;
	}

	public void setTransDetailPaymentId(Integer transDetailPaymentId) {
		this.transDetailPaymentId = transDetailPaymentId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "MEMBERSHIP_ID")
	public Membership getMembership() {
		return this.membership;
	}

	public void setMembership(Membership membership) {
		this.membership = membership;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "TRANS_PAYMENT_ID", nullable = false)
	public TransPayment getTransPayment() {
		return this.transPayment;
	}

	public void setTransPayment(TransPayment transPayment) {
		this.transPayment = transPayment;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "TRANS_DETAIL_ID", nullable = false)
	public TransactionDetail getTransactionDetail() {
		return this.transactionDetail;
	}

	public void setTransactionDetail(TransactionDetail transactionDetail) {
		this.transactionDetail = transactionDetail;
	}

	@Column(name = "PAYMENT_AMT", precision = 18, scale = 4)
	public BigDecimal getPaymentAmt() {
		return this.paymentAmt;
	}

	public void setPaymentAmt(BigDecimal paymentAmt) {
		this.paymentAmt = paymentAmt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_DTTM", nullable = false, length = 19)
	public Date getLastUpdatedDttm() {
		return this.lastUpdatedDttm;
	}

	public void setLastUpdatedDttm(Date lastUpdatedDttm) {
		this.lastUpdatedDttm = lastUpdatedDttm;
	}

	@Column(name = "LAST_UPDATED_BY_ID", nullable = false, length = 100)
	public String getLastUpdatedById() {
		return this.lastUpdatedById;
	}

	public void setLastUpdatedById(String lastUpdatedById) {
		this.lastUpdatedById = lastUpdatedById;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DTTM", nullable = false, length = 19)
	public Date getCreatedDttm() {
		return this.createdDttm;
	}

	public void setCreatedDttm(Date createdDttm) {
		this.createdDttm = createdDttm;
	}

	@Column(name = "CREATED_BY_ID", nullable = false, length = 100)
	public String getCreatedById() {
		return this.createdById;
	}

	public void setCreatedById(String createdById) {
		this.createdById = createdById;
	}

	@Column(name = "CREDIT_TRANS_DETAIL_ID")
	public Integer getCreditTransDetailId() {
		return this.creditTransDetailId;
	}

	public void setCreditTransDetailId(Integer creditTransDetailId) {
		this.creditTransDetailId = creditTransDetailId;
	}

}
